### ISSUE TITLE
Incorrect examples of alertmanager heartbeat

### ISSUE THREAD

**Issue by alxrem** [alertmixer/amixr#79]
Examples of alertmanager heartbeat config has inconsistent names of objects and wrong indentation of route config.

Examples
```
            groups:
                - name: meta
                  rules:
                    - alert: amix-heartbeat  <- doesn't match alertname
                      expr: vector(1)
                      labels:
                        severity: none
                      annotations:
                        description: This is heartbeat alert
                        summary: Alerting Amixr
```
```
            ...
            route:
            ...
                routes:
                - match:
                    alertname: heartbeat
                    receiver: 'heartbeat'  <- doesn't match receiver name and should be indented as "match:"
                    group_wait: 0s
                    group_interval: 1m
                    repeat_interval: 50s
            receivers:
            - name: 'amixr-heartbeat'
            webhook_configs:
```
should looking as
```
groups:
- name: meta
  rules:
  - alert: heartbeat
    expr: vector(1)
      . . .
```
```
...
route:
...
  routes:
  - match:
      alertname: heartbeat
    receiver: 'amixr-heartbeat'
    group_wait: 0s
    group_interval: 1m
    repeat_interval: 50s
receivers:
- name: 'amixr-heartbeat'
```
